<LoadingScreen>:
    md_bg_color: 1,1,1,1
    MDLabel:
        text: 'loading...'
        bold: True
        font_size: '16dp'
        halign: 'center'
        opacity: 0
        id: labe
        md_bg_color: 1,1,1,1
        
    MDSpinner:
        active: True
        size_hint: None, None
        height: '30dp'
        width: '30dp'
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        id: spin